
import Express from 'express';
import { JsonDB, Config } from 'node-json-db';
import type { Context } from 'openapi-backend';

// db package used `node-json-db` 
// npmjs.com/package/node-json-db
// `messages.json` is autogenerated file by the packages, as described here
const db = new JsonDB(new Config('messages', true, false, '/'));

module Messages {

    /**
     * Post a message to the database in `messages.json` file
     */
    export function postMessageToDB(
        c: Context,
        req : Express.Request,
        res: Express.Response
        ) {
            // const data = db.push('/test', req.body, false);
            // adding rando id + body
            db.push("/" + Math.random(), req.body, false);
            return res.status(200).json({ code: 200, result: "success"});
      }

      /**
       * Read all the messages from the database
       */
    
      export function getMessagesFromDB(
        c: Context,
        req : Express.Request,
        res: Express.Response
        ) {
            db.reload();
            db.getObject<any>("/").then( (result) => {
                return res.status(200).json({code: 200, result: result });
            });
        }

        /**
         * Not found
         */
        export function notFound (
            c: Context,
            req : Express.Request,
            res: Express.Response
        ) {
            res.status(404).json({ code: 404, result: 'Not found' })
        }

        /**
         * Validation failed handler
         */
        export function validationFail(
            c: Context,
            req: Express.Request, 
            res: Express.Response
        ) {
            return res.status(400).json({ code: 400, result: 'Bad request' });
        }
} 

export default Messages;