openapi: 3.0.0
info:
  title: Chat Messenger API
  version: 1.0.0
paths:
  /messages:
    get:
      operationId: getMessages
      summary: Get all messages
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: string
        '400':
          description: Bad request
    post:
      operationId: postMessage
      summary: Send a new message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                user:
                  type: string
      responses:
        '200':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  result:
                    type: string
        '400':
          description: Bad request, invalid input